user_homepage:
    path:     /profil
    defaults: { _controller: UserBundle:Default:index }
user_registration:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }
login_route:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: UserBundle:Security:login_check }
